name: onboard_sdk
description: A Dart package designed to facilitate seamless interaction with the Onboard Project server API.
version: 1.3.0
repository: https://github.com/onboard-project/sdk

environment:
  sdk: ^3.7.2

dependencies:
  latlong2: ^0.9.1
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
